[package]
name = "flood-fill"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
askama = "0.12.1"
clap = { version = "4.5.31", features = ["derive"] }
image = "0.25.5"
proj = "0.28.0"
